; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24234.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\s2862\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
